[phases.setup]
nixPkgs = ["python311"]
aptPkgs = ["postgresql"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Python Flask 빌드 완료'"]

[start]
cmd = "gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT api.community_api:app"

[variables]
NIXPACKS_NO_CACHE = "1"
